### ISSUE TITLE
for loop 

### ISSUE THREAD

**Issue by kiranmayee18** [harry-7/Decaf-Compiler#4]
For loop doesnt run from 0 to a variable (it throws an error and no IR is generated). However doing variable - 0 works. 
![errorscreenshot](https://user-images.githubusercontent.com/33979956/45875870-8ea9f280-bdb6-11e8-876a-df6a86c5dede.png)

**Comment by hkveeranki** [comment]
Thanks for reporting.
fixed in https://github.com/harry-7/Decaf-Compiler/commit/a84d10fcbeb504facb1f2f2a6747ebcf62bf947f
