### ISSUE TITLE
multiple arguments for a function

### ISSUE THREAD

**Issue by kiranmayee18** [harry-7/Decaf-Compiler#5]
unable to send multiple arguments to a function.
eg: running the input_gcd code present in the sample_input directory gives the following error : 
![errorscreenshot](https://user-images.githubusercontent.com/33979956/45880843-f23c1c00-bdc6-11e8-854d-aa231e49678a.png)

Also, no IR is generated

**Comment by hkveeranki** [comment]
Thanks for reporting.
fixed in a84d10f
